//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerPrint.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FingerPrint.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 圆型 的本地化字符串。
        /// </summary>
        public static string DT_circle {
            get {
                return ResourceManager.GetString("DT_circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自由绘制 的本地化字符串。
        /// </summary>
        public static string DT_free {
            get {
                return ResourceManager.GetString("DT_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直线 的本地化字符串。
        /// </summary>
        public static string DT_line {
            get {
                return ResourceManager.GetString("DT_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多边形 的本地化字符串。
        /// </summary>
        public static string DT_polygon {
            get {
                return ResourceManager.GetString("DT_polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矩形 的本地化字符串。
        /// </summary>
        public static string DT_rectangle {
            get {
                return ResourceManager.GetString("DT_rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能识别模式 的本地化字符串。
        /// </summary>
        public static string DT_smart {
            get {
                return ResourceManager.GetString("DT_smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string FO_clear {
            get {
                return ResourceManager.GetString("FO_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放弃 的本地化字符串。
        /// </summary>
        public static string FO_giveup {
            get {
                return ResourceManager.GetString("FO_giveup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整和缩放 的本地化字符串。
        /// </summary>
        public static string FO_modify {
            get {
                return ResourceManager.GetString("FO_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 的本地化字符串。
        /// </summary>
        public static string FO_read {
            get {
                return ResourceManager.GetString("FO_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复 的本地化字符串。
        /// </summary>
        public static string FO_restore {
            get {
                return ResourceManager.GetString("FO_restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string FO_save {
            get {
                return ResourceManager.GetString("FO_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        public static string MN_menu {
            get {
                return ResourceManager.GetString("MN_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-CN 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已保存！ 的本地化字符串。
        /// </summary>
        public static string TP_saved {
            get {
                return ResourceManager.GetString("TP_saved", resourceCulture);
            }
        }
    }
}
